version: '3'
services:
  postgres:
    image: postgres:11.3
    volumes:
      - security:/var/lib/postgres
      - ./docker-compose-artifacts/postgres:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test
    ports:
      - 5432:5432/tcp
volumes:
  security: