#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/test?currentSchema=security
#    username: test
#    password: 123456
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    open-in-view: false
#    properties:
#      hibernate:
#        temp:
#          use_jdbc_metadata_defaults: "false"
#        dialect: org.hibernate.dialect.PostgreSQL95Dialect
#        format_sql: "true"
#    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: "false"

server:
  port: 8082
